DROP TABLE IF EXISTS users,products,meals,meal_products;


CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    gender VARCHAR(50) NOT NULL CHECK (gender IN ('WOMEN', 'MEN')),
    email VARCHAR(255) NOT NULL UNIQUE,
    age SMALLINT,
    weight FLOAT,
    height FLOAT,
    target VARCHAR(50) NOT NULL CHECK (target IN ('LOSE_WEIGHT', 'MAINTAIN_WEIGHT', 'GAIN_WEIGHT')),
    calories FLOAT
);

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    calories_per_portion FLOAT,
    squirrels FLOAT,
    fats FLOAT,
    carbohydrates FLOAT
);

CREATE TABLE meals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_time TIMESTAMP NOT NULL,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE);

CREATE TABLE meal_products (
    meal_id BIGINT REFERENCES meals(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    PRIMARY KEY (meal_id, product_id)
    );